export const INIT_WEBSOCKET = 'INIT_WEBSOCKET'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_SOURCE = 'SET_SOURCE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_IS_WX = 'SET_IS_WX'
export const SET_IS_ALIPAY = 'SET_IS_ALIPAY'
export const SET_IS_APP = 'SET_IS_APP'
export const IS_FIRST_ROUTER = 'IS_FIRST_ROUTER'
